# 引用镜像
FROM node:latest
# 作者
MAINTAINER crx

# 执行命令，创建文件夹
RUN mkdir -p /var/publish/nest
# 将nestapi目录拷贝到镜像里，也可用COPY命令
ADD ./nestapi /var/publish/nest
# 执行镜像的工作目录
WORKDIR /var/publish/nest

# 配置系统变量，指定端口
ENV HOST 0.0.0.0

# 开放端口
EXPOSE 3002

# 容器启动命令
CMD ["node","dist/main.js"]